environment:
  matrix:
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm prune
  - npm run bootstrap

test_script:
  - npm test

after_test:
  - npm run codecov

build: off
deploy: off

